import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Top bar */}
        <header
          style={{
            padding: "1rem",
            background: "#111",
            color: "#fff",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <div>MechGamicus</div>
          <nav>
            <a href="/" style={{ marginRight: "1rem", color: "#fff" }}>
              Dashboard
            </a>
          </nav>
        </header>

        <div style={{ padding: "2rem" }}>{children}</div>
      </body>
    </html>
  );
}
